# Generated by Django 2.2 on 2021-07-11 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('1', 'DNI'), ('2', 'Carnet de Extrangeria')], max_length=1)),
                ('num_document', models.CharField(max_length=9)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apePaterno', models.CharField(blank=True, max_length=100)),
                ('apeMaterno', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, choices=[('0', 'FEMENINO'), ('1', 'MASCULINO')], max_length=1)),
                ('celular', models.CharField(blank=True, max_length=9)),
                ('fechaPrimeraDosis', models.DateField(blank=True)),
                ('fechaSegundaDosis', models.DateField(blank=True)),
                ('userDiresa', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
